# Generated by Django 5.2.6 on 2025-11-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(max_length=50)),
                ('is_on', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RoomMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('GAMER', 'Gamer Mode'), ('STUDY', 'Study Mode'), ('CHILL', 'Chill Mode'), ('SLEEP', 'Sleep Mode'), ('STREAM', 'Stream Mode')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('led_color_hex', models.CharField(default='#FFFFFF', max_length=7)),
                ('brightness', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SensorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
